#!/usr/bin/env bash
# Claude Context Configuration

CLAUDE_CONTEXT_MODE="history"
CLAUDE_ENABLE_CACHE="true"
CLAUDE_INJECT_PROBABILITY="1.0"
CLAUDE_HOME="${HOME}/.claude"
CLAUDE_HOOKS_DIR="${CLAUDE_HOME}/hooks"
CLAUDE_HISTORY_DIR="${CLAUDE_HOME}/history"
CLAUDE_SUMMARY_DIR="${CLAUDE_HOME}/summaries"
CLAUDE_CACHE_DIR="${XDG_CACHE_HOME:-${HOME}/.cache}/claude-context"
CLAUDE_LOG_DIR="${CLAUDE_HOME}/logs"
CLAUDE_LOCK_TIMEOUT="5"
CLAUDE_CACHE_MAX_AGE="3600"

export CLAUDE_CONTEXT_MODE
export CLAUDE_ENABLE_CACHE
export CLAUDE_INJECT_PROBABILITY
export CLAUDE_HOME
export CLAUDE_HOOKS_DIR
export CLAUDE_HISTORY_DIR
export CLAUDE_SUMMARY_DIR
export CLAUDE_CACHE_DIR
export CLAUDE_LOG_DIR
export CLAUDE_LOCK_TIMEOUT
export CLAUDE_CACHE_MAX_AGE
